# Site settings
title: Just a blog
email: gmauricio.munoz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a blog
baseurl: /blog
url: "http://gmaurcio.github.io" # the base hostname & protocol for your site
twitter_username: mauriciomunoz
github_username:  gmauricio

# Build settings
markdown: kramdown
